apiVersion: v1
kind: Service
metadata:
  name: mongo-arm64
  namespace: mongo-vault-operator
spec:
  selector:
    app: mongo-arm64
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-arm64
  namespace: mongo-vault-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-arm64
  template:
    metadata:
      labels:
        app: mongo-arm64
    spec:
      containers:
        - name: mongo-arm64
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "example"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
