apiVersion: v2
name: mongodb
description: A Helm chart for MongoDB with authentication enabled
type: application
version: 0.1.0
appVersion: "7.0"

dependencies:
  - name: mongodb
    version: "13.18.5"
    repository: "https://charts.bitnami.com/bitnami"
