apiVersion: v2
name: vault
description: A Helm chart for HashiCorp Vault
type: application
version: 0.1.0
appVersion: "1.15.2"

dependencies:
  - name: vault
    version: "0.25.0"
    repository: "https://helm.releases.hashicorp.com"
