vault:
  global:
    enabled: true
    namespace: mongo-vault-operator
  
  server:
    dev:
      enabled: true
      devRootToken: "root-token"
    
    standalone:
      enabled: false
    
    ha:
      enabled: false
    
    service:
      enabled: true
      type: ClusterIP
      port: 8200
      targetPort: 8200
    
    dataStorage:
      enabled: true
      size: 10Gi
      storageClass: ""
    
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m

  ui:
    enabled: true
    serviceType: "ClusterIP"
    serviceNodePort: null
    externalPort: 8200

  injector:
    enabled: true
    replicas: 1
    port: 8080
    
    webhook:
      failurePolicy: Ignore
      
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m

namespace: mongo-vault-operator
